insert into PersonalTvAzteca values ('Irivng Arturo','Guzman','Flores')
insert into PersonalTvAzteca values ('Miguel Angel','Guzman','Flores')
insert into PersonalTvAzteca values ('Juan Eduardo','Guzman','Flores')
insert into PersonalTvAzteca values ('Aldair','Flores','Huerta')
insert into PersonalTvAzteca values ('Diana Trinidad','Flores','Sosa')